eureka:
  client:
    service-url:
      #     配置服务注册中心集群时，此处可以配置多个地址(通过逗号隔开)
      defaultZone: http://localhost:8762/eureka/,http://localhost:876/eureka/
#  instance:
#    hostname: clientName

# spring.application.name,这个很重要，在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: client

server:
  port: 2000